# Generated by Django 4.1.13 on 2024-11-02 14:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_curso', models.IntegerField()),
                ('apresent', models.TextField()),
                ('said_prof', models.TextField()),
                ('planocur', djongo.models.fields.JSONField()),
                ('avqual', djongo.models.fields.JSONField(default=list)),
                ('outr_inf', djongo.models.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=255)),
                ('sem', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('ht', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Unidades Curriculares',
            },
        ),
    ]
